# Generated by Django 5.0.6 on 2024-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'Odam',
                'verbose_name_plural': 'Odamlar',
            },
        ),
    ]
