# Generated by Django 5.0.6 on 2024-07-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_human'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image'),
        ),
    ]
